boxsdk/object/events.py
boxsdk/util/lru_cache.py
test/unit/util/test_lru_cache.py

I think it's wrong to return any value if the key doesn't exist in the cache since there's no good way to differentiate it from the actual value stored in cache.

Improved the LRUCache class and added dostrings

---

README.rst
setup.py
test/unit/object/test_folder.py

Also, tweak README.rst to remove an unexpected indentation problem.
Bump version to 1.0.2.

Fix failing pypy tests.

---

boxsdk/object/base_object.py
boxsdk/object/group.py
test/unit/object/test_group.py

All clients to know exactly when GET calls might be triggered when
one of the pageable-APIs is used. This is achieved by returning
information about the *current* page on each call to 'next()' of
the underlying generator. The first call might return:
<object>, 10, 0
indicating this object is the 0th indexed item in the current page
that has 10 items. This means that previous API returned info
about 10 such items. The subsequent call to next() would return:
<object>, 10, 1
And so forth. Eventually returning:
<object>, 10, 9
At this point, the next time next() is called a new GET request
will be trigger in order to fetch the next *page* of results. This
might then return:
<object>, 12, 0
indicating that this next *page* has 12 results.

Improve the paging API

---

boxsdk/object/collaboration.py

- based on https://developers.box.com/docs/#collaborations-collaboration-object
and my own development testing the values should be lowercase and the
uploader-combo roles should have a space instead of a hyphen.

fix collaboration role values

---

.travis.yml
HISTORY.rst
boxsdk/object/search.py
setup.py
test/unit/object/test_search.py

Include support for type and content_types fields.

Improve search endpoint.

---

boxsdk/object/file.py
boxsdk/object/folder.py
test/unit/object/conftest.py
test/unit/object/test_file.py
test/unit/object/test_folder.py

Add preflight option to update_contents_with_stream and update_contents,
so files can be updated with optional preflight check before actually
uploading all the bytes.

Add preflight option for updating files

---

boxsdk/exception.py
boxsdk/session/box_session.py
test/unit/test_exception.py

For example when trying you create a folder that already exists you will get back a list of conflicts in the context_info in the response.

It would be helpful to include context_info in the BoxAPIException

---

boxsdk/object/item.py
test/unit/object/test_item.py

Make the return type match the type specified in the docstring.  The
method was previously attempting to return ``unicode or None``.
The method was also previously attempting to access the 'url' item on
the shared_link object. However, the Box API returns a null object when
the shared link is disabled [1]. Make the method check for success by
doing an ``is None`` check on the shared_link object.
[1] https://box-content.readme.io/#create-a-shared-link-for-a-folder

Return bool from `Item.remove_shared_link()`.

---

test/functional/test_rate_limits.py
test/functional/test_recovery.py
test/functional/test_token_refresh.py
test/integration/test_retry_and_refresh.py

Some tests were calling `Client.folder()` with a `folder_id` argument of 0. However, that parameter is supposed to be of type `unicode`, not `int`.
Correct all occurrences of `folder(0)` to `folder('0')`.

Correct test invocations of Client.folder()

---

HISTORY.rst
README.rst
boxsdk/client.py
boxsdk/object/base_endpoint.py
boxsdk/object/base_object.py
boxsdk/object/group_membership.py
boxsdk/object/metadata.py
boxsdk/session/box_session.py
boxsdk/util/shared_link.py
docs/source/boxsdk.util.rst
test/conftest.py
test/integration/conftest.py
test/integration/test_as_user.py
test/integration/test_with_shared_link.py
test/unit/conftest.py
test/unit/object/test_metadata.py
test/unit/object/test_search.py
test/unit/test_exception.py
test/unit/util/test_shared_link.py
tox.ini

The Box API supports enterprise admins making requests as users via the As-User header.
It also supports gaining access to items via a shared link via the BoxApi: shared_link= header.
This commit adds an `as_user` and `with_shared_link` method to the SDK client, session, and endpoint objects
to support a fluent interface for adding the appropriate headers to requests.
For example, to get user with id 1234's root folder info:
client.as_user(User('1234')).folder('0').get()

Add support for As-User and shared items headers.

---

boxsdk/object/events.py
test/unit/object/test_events.py

Catch requests Timeout instead of urllib3 TimeoutError

---

boxsdk/object/item.py
test/unit/object/test_item.py

Resolves Issue #65 by adding support for shared_link passwords.

Adding support for shared_link password parameter

---

.gitignore
.travis.yml
.travis/install.sh
.travis/run.sh
HISTORY.rst
README.rst
requirements.txt
setup.py
tox.ini

Add support and testing for:
- CPython 3.5
- cryptography>=1.0 on PyPy 2.6.0.
PyPy 2.6 isn't available by default on Travis CI. Only PyPy 2.5 is, but that is incompatible with cryptography>=1.0 [1].
Borrow some of the Travis CI setup from the PyCA's cryptography project [2], which installs pyenv [3] in order to bootstrap an installation for PyPy 2.6.
[1] <https://github.com/travis-ci/travis-ci/issues/4756>
[2] <https://github.com/pyca/cryptography/tree/master/.travis>
[3] <https://github.com/yyuu/pyenv>

Add support for py35, pypy with cryptography>=1.0

---

README.rst
boxsdk/auth/jwt_auth.py
requirements-dev.txt
test/unit/auth/test_jwt_auth.py

This parameter is referred to as `enterprise_id` in the Box Developer documentation. Also, the noun "token" is already used to refer to the data returned at the end of the auth process. So rename this to reduce confusion.
This is a backwards compatible change, because the method parameter name was already correct. This is only a change to private attributes, test code, and documentation.
Also add a temporary pip version exclusion on the latest version of pytest, which is broken on Python 2. See https://github.com/pytest-dev/pytest/issues/1085 and https://github.com/pytest-dev/pytest/issues/1035.

Rename uses of enterprise_token to enterprise_id

---

HISTORY.rst
boxsdk/session/box_session.py
boxsdk/util/multipart_stream.py
docs/source/boxsdk.util.rst
requirements.txt
test/conftest.py
test/functional/conftest.py
test/functional/test_delete.py
test/functional/test_file_upload_update_download.py
test/unit/session/test_box_session.py
test/unit/util/test_multipart_stream.py
test/util/__init__.py
test/util/streamable_mock_open.py

Currently, requests only supports streaming uploads by chunking them.
This commit utilizes the requests_toolbelt's MultipartEncoder to use
multipart-form uploads while still streaming the data from disk.
Fixes #84.

Stream uploads from disk.

---

HISTORY.rst
README.rst
boxsdk/auth/cooperatively_managed_oauth2.py
boxsdk/auth/oauth2.py
boxsdk/auth/redis_managed_oauth2.py
boxsdk/auth/remote_managed_oauth2.py
boxsdk/auth/remote_oauth2.py
boxsdk/network/logging_network.py
boxsdk/util/log.py
demo/auth.py
demo/cooperative_auth.py
demo/example.py
demo/music_player.py
docs/source/boxsdk.auth.rst
docs/source/boxsdk.network.rst
docs/source/boxsdk.util.rst
requirements.txt
setup.py
test/conftest.py
test/functional/test_file_upload_update_download.py
test/unit/auth/test_cooperatively_managed_oauth2.py
test/unit/auth/test_jwt_auth.py
test/unit/auth/test_redis_managed_oauth2.py
test/unit/auth/test_remote_managed_oauth2.py
test/unit/network/conftest.py
test/unit/network/test_logging_network.py
test/unit/network/test_network.py
test/unit/util/test_multipart_stream.py
test/util/streamable_mock_open.py

- Adds LoggingNetwork to allow clients to see what network calls the SDK is making.
- Adds RemoteOAuth2 to allow auth to occur in a different process or machine from the SDK.
- Adds RedisManagedOAuth2 to allow token storage in Redis, to enable multiple processes or machines to share tokens.
- Addresses issue #71 with `CooperativelyManagedOAuth2Mixin` class.

Add network and auth subclasses.

---

setup.py

requests-toolbelt was added to the requirements.txt but not setup.py.
Is there a reason that both are needed or could it be consolidated to just using requirements.txt.

Add requests-toolbelt to setup.py

---

HISTORY.rst
boxsdk/util/log.py
setup.py
test/unit/network/test_logging_network.py
test/unit/util/test_log.py
tox.ini

On Python 3, calling `setup_logging()` in `boxsdk.util.log`
would always raise
NameError: name 'basestring' is not defined
On Python 3, this prevented `LoggingNetwork` from being
initialized without passing an existing `Logger`.
Replace this usage of `basestring` with the equivalent
`six.string_types`.
Add unit test coverage of `boxsdk.util.log`.
Bump version to 1.3.2.

Replace `basestring` with `six.string_types`

---

README.rst
boxsdk/object/events.py
boxsdk/util/enum.py
boxsdk/util/text_enum.py
test/unit/object/test_events.py
test/unit/util/test_enum.py

Add a `stream_type` parameter to the `generate_events_with_long_polling()` method and its helper
methods. This allows users to listen to other event stream types. The default is still to listen to the 'all' stream.
In order to differentiate between user and enterprise event streams, the following enum hierarchy was created, with the help of a new `ExtendableEnumMeta` metaclass:
```
+-- `EventsStreamType`
|
+-- `UserEventsStreamType`
|
+-- `EnterpriseEventsStreamType`
```
Unrelatedly, fix up the RST for the README. Add a table of contents, and fix up backticks (double-backticks are needed to create code spans, single-backticks aren't enough).

Add stream_type param for events long polling

---

HISTORY.rst
boxsdk/object/file.py
boxsdk/object/item.py
setup.cfg
setup.py
test/unit/object/conftest.py
test/unit/object/test_file.py
test/unit/object/test_item.py

Expose file.get_shared_link_download_url method.

---

README.rst

This is an addendum to #114 (which addressed #110) and merely adds documentation for the new `get_shared_link_download_url()` method to the top-level README, along with clarification for which types of items (files and/or folders) `get_shared_link()` and `get_shared_link_download_url()` can be used.

Add get_shared_link_download_url() documentation/example to README

---

README.rst
setup.py

Update README with info about ``make_request``.

Bump to version 1.4.2.

---

HISTORY.rst
MANIFEST.in
README.rst
boxsdk/exception.py
setup.cfg
setup.py
test/functional/conftest.py
test/unit/auth/test_oauth2.py
tox.ini

Create wheel with correct conditional dependencies and license file.
Change the ``license`` meta-data from the full license text, to just a short string, as specified in [1][2].
Include entire test/ directory in source distribution. test/__init__.py was previously missing.
Update documentation. Fixes #112.
Use utf-8 encoding to open README in setup.py.
Run pep8 and pylint on setup.py.
Update pylint directives.
[1] <https://docs.python.org/3.5/distutils/setupscript.html#additional-meta-data>
[2] <https://www.python.org/dev/peps/pep-0459/#license>

Additional changes for 1.4.2 release

---

HISTORY.rst
boxsdk/auth/developer_token_auth.py
boxsdk/auth/oauth2.py
boxsdk/version.py
test/unit/auth/test_oauth2.py

Fixes #124
The Box API includes a /revoke endpoint to de-auth tokens.
This commit makes it easy to use this endpoint with the SDK.

Add revoke() method to OAuth2 class.

---

HISTORY.rst
boxsdk/auth/oauth2.py
boxsdk/auth/redis_managed_oauth2.py
boxsdk/version.py
requirements-dev.txt
test/conftest.py
test/unit/auth/test_jwt_auth.py
test/unit/auth/test_oauth2.py
test/unit/auth/test_redis_managed_oauth2.py
test/unit/network/test_logging_network.py

If the protected method `_get_tokens()` returns new tokens, refresh is skipped, and those tokens are used.
Previously, we would return the new tokens without updating the object state. Subsequent uses of the `OAuth2` object would use the old tokens.
Now we will correctly update the object state.
Fixes #128.
Also make some minor test fixes and upgrade the version of mock that we use.
Prepare for bump to version 1.5.2.

Always update `OAuth2` object with new tokens

---

HISTORY.rst
boxsdk/auth/jwt_auth.py
boxsdk/version.py
test/unit/auth/test_jwt_auth.py

Open the PEM private key file in 'rb' mode so that `.read()` returns `bytes` in Python 3. Otherwise, the default `openssl` backend of `cryptography` fails to use the key.
Set the `_user_id` attribute to `None` when authenticating an enterprise instance.
Fixes #136.
cc @makiten

Fixes to JWTAuth

---

boxsdk/auth/jwt_auth.py
boxsdk/object/file.py
boxsdk/object/folder.py
boxsdk/object/group.py
boxsdk/object/group_membership.py
boxsdk/object/item.py
boxsdk/object/search.py

Enabled `Translator` to register new subclasses of smart objects.  Removed all hard coded smart object return types in favor of a lookup in `Translator` or returning an instance of `self.__class__`.

Allow custom subclasses of smart objects

---

boxsdk/auth/jwt_auth.py
boxsdk/client/client.py
boxsdk/object/base_api_json_object.py

Enable custom subclasses of smart objects to be registered correctly with the `Translator`.

Register subclasses

---

boxsdk/client/client.py

For consistency with other objects, can use `client.collaboration('box_id').do_something(...)` the same way we do with `Folder`, `File`, etc.

Add collaboration() method to Client.

---

AUTHORS.rst
HISTORY.rst
boxsdk/exception.py
boxsdk/network/default_network.py
boxsdk/object/base_api_json_object.py
boxsdk/object/cloneable.py
boxsdk/version.py
docs/source/boxsdk.object.rst
docs/source/boxsdk.util.rst

Bump version to 2.0.0a1.
Add @kelseymorris95 to AUTHORS.
Fix up docstrings for Sphinx, and update docs sources.
Clean up release notes.

Prepare for alpha release of 2.0.0

---

boxsdk/network/default_network.py
boxsdk/network/logging_network.py
boxsdk/network/network_interface.py
test/conftest.py
test/functional/conftest.py
test/integration/conftest.py
test/unit/auth/test_jwt_auth.py
test/unit/network/conftest.py
test/unit/network/test_logging_network.py
test/unit/network/test_network.py

Move response logging to a new `LoggingNetworkResponse` class.
This allows us to decide whether to log the response body, based
on whether the caller reads or streams the content. This fixes a
bug introduced by Pull Request #166, where the `LoggingNetwork`
would always omit logging the response body.
Add a `network_response_constructor` property to
`DefaultNetwork`, to make it easier for subclasses to return
their own `NetworkResponse` subclasses. Use this in
`LoggingNetwork`, to return `LoggingNetworkResponse` instances.
Also add it as an optional property on the `Network` interface
class.
In `network_interface.py`, switch some usages of
`@abc.abstractmethod` to `@abc.abstractproperty`. This doesn't
matter on recent versions of Python 3, but there is a difference
between the two on …

Logging refactors and improvements

---

README.rst
boxsdk/auth/jwt_auth.py
boxsdk/session/box_session.py
requirements.txt
test/unit/auth/test_jwt_auth.py
test/unit/session/test_box_session.py

Rename `JWTAuth.authenticate_app_user()` to
`JWTAuth.authenticate_user()`, to reflect the fact that the new
Box service accounts can authenticate as managed users as well
as app users. `JWTAuth.authenticate_app_user()` is retained as
an alias, for backwards-compatability.
Allow a user ID to be passed to `JWTAuth`, instead of a `User`
object. Previously, developers would need to import and manually
construct a `boxsdk.object.user.User`, since `Client.user()`
cannot be used until the `Client` has been constructed (which is
usually done after all authentication is complete).
Allow a user or user ID to be passed to the `JWTAuth`
constructor. This way, `JWTAuth.authenticate_user()` can be
called without any arguments. More importantly, this means that
`JWTAuth.refresh()` can be called …

Refactors to JWTAuth

---

.gitignore
.pylintrc
.travis.yml
.travis/install.sh
HISTORY.rst
README.rst
boxsdk/object/api_json_object.py
boxsdk/object/events.py
boxsdk/util/compat.py
boxsdk/util/enum.py
boxsdk/version.py
setup.py
test/functional/mock_box/util/chaos_utils.py
test/unit/util/test_compat.py
test/unit/util/test_enum.py
tox.ini

Bump version to 2.0.0a3.
Add new release notes.
gitignore more patterns for Python virtualenv directories.
Start running tests against the development build of Python 3.6
(which is currently in a feature-freeze beta).
`six.with_metaclass()` doesn't work with `enum.EnumMeta` in
Python 3.6, because of logic that was added to
`EnumMeta.__prepare__()`. The six bug actually applies to all
versions of Python 3, but I guess it was never noticed until
now.
This adds our own `with_metaclass()` helper function, with the
fix applied to it. Later I'll submit the same patch to six.
Explanation of the bug and the fix are in the docstring.
jsonpatch is not currently compatible with Python 3.6. If we
can't load it during functional testing, then
`@chaos_utils.patch()` will be a no-op.

Prepare for next 2.0.0 alpha release

---

boxsdk/object/folder.py
boxsdk/pagination/__init__.py
boxsdk/pagination/box_object_collection.py
boxsdk/pagination/limit_offset_based_object_collection.py
boxsdk/pagination/marker_based_object_collection.py
boxsdk/pagination/page.py
test/unit/object/test_folder.py
test/unit/pagination/__init__.py
test/unit/pagination/box_object_collection_test_base.py
test/unit/pagination/test_limit_offset_based_object_collection.py
test/unit/pagination/test_marker_based_object_collection.py
test/unit/pagination/test_page.py

Enable marker based pagination in the SDK, explicitly required for the [new Recents API](https://developer.box.com/v2.0/reference#get-recent-items)
Recents isn't compatible with the typical [limit/offset paging](https://developer.box.com/v2.0/reference#offset-based-paging) that most other endpoints use, and so [marker-based paging](https://developer.box.com/v2.0/reference#marker-based-paging) must be enabled. This PR adds explicit classes to support Limit/Offset pagination, as well as Marker pagination.

Limit/Offset and Marker Based pagination

---

boxsdk/client/client.py
boxsdk/object/__init__.py
boxsdk/object/recent_item.py
boxsdk/pagination/page.py
test/unit/client/test_client.py
test/unit/object/test_recent_item.py

See: https://developer.box.com/v2.0/reference#recent-item-object
Use the Client to retrieve a user's recently accessed items on Box.
`RecentItem` class allows the translator to correctly instantiate the item returned by the API, which has the field `type='recent_item'`. This provides some additional fields, and access to the underlying File/Folder as the property `RecentItem.item`

Add new Recents API to client

---

.gitignore
.pylintrc
.travis.yml
.travis/install.sh
.travis/run.sh
HISTORY.rst
README.rst
boxsdk/auth/jwt_auth.py
boxsdk/auth/oauth2.py
boxsdk/object/events.py
boxsdk/util/compat.py
boxsdk/util/enum.py
boxsdk/version.py
requirements-dev.txt
requirements.txt
setup.cfg
setup.py
test/functional/mock_box/util/chaos_utils.py
test/unit/util/test_compat.py
test/unit/util/test_enum.py
tox.ini

Fixes #197 in v1.5.
Pull in repo config changes from master branch.
Add testing support for Python 3.6, and upgrade PyPy tests to
use PyPy2.7 5.8.0.
Lock sphinx to a version that still supports Python 2.6. (In the
future, on the master branch, we should exclude the sphinx
install from CI jobs that don't use it, and use Python 3.6 for
the job that does require sphinx.)
Add new pattern to .gitignore, update configs in .pylintrc, add
isort config.
Add versioning note to README.
Cherry pick Python3.6 support from master branch.
Bump version to 1.5.4

Fix JWT Token Refresh and bump version to 1.5.4

---

HISTORY.rst
boxsdk/util/api_call_decorator.py
boxsdk/version.py
test/unit/util/test_api_call_decorator.py

This magic method was previously returning a plain, unbound
function. This tricks some introspection code, which expects it
to be a bound method.
Also add unit test coverage for that module.
Bump version to 2.0.0a6.

APICallWrapper.__get__ must return a bound method

---

HISTORY.rst
boxsdk/object/file.py
boxsdk/object/folder.py
test/functional/mock_box/behavior/file_behavior.py
test/unit/object/conftest.py
test/unit/object/test_file.py
test/unit/object/test_folder.py

Upload responses look like {"entries": [{"type": "file", ...}]},
not {"type": "file", ...}. However, the code for uploading a new
file version was incorrectly assuming the latter, causing it to
return File({"entries": [{"type": "file", ...}]}) instead of
File({"type": "file", ...}).
Now we will expand the "entries", and grab only the file object.
We'll also be future-proof, in case a future version of the API
starts returning {"type": "file", ...}.
Fixes #150.

Correctly handle upload responses

---

HISTORY.rst
boxsdk/auth/jwt_auth.py
boxsdk/util/compat.py
test/unit/auth/test_jwt_auth.py
test/unit/util/test_api_call_decorator.py

This allows a `JWTAuth` object to be initialized, without
requiring that the key be available to the process on disk.
Fixes #177.

Support for passing RSA private key to JWTAuth

---

HISTORY.rst
boxsdk/auth/oauth2.py
boxsdk/version.py
pytest.ini
test/unit/auth/test_oauth2.py
tox.ini

Auth objects can now be closed, which prevents them from being
used to request new tokens. This will also revoke any existing
tokens. Also introduces a `closing()` context manager method,
which will auto-close the auth object on exit. Clients can use
this to make sure that their tokens don't live longer than they
need them for.

Add functionality for auto-revoking auth tokens

---

.pylintrc
boxsdk/util/compat.py
test/unit/util/test_compat.py

Add a fallback for `six.raise_from`, which isn't available in
six 1.4.0. It isn't available until six 1.9.0. We could also
have raised the lower bound for the six requirement, but this is
an easy way to allow clients to keep using their existing
versions of six.
Fix support for the latest version of six, 1.11.0. That release
changed the temporary metaclass returned from
`with_metaclass()`, such that it directly inherits from `type`,
instead of inheriting from the target metaclass [1]. We depended
on this detail, and the change caused
.. code-block:: python
TypeError('metaclass conflict: ...')
to be raised when defining a class with `with_metaclass()`. We
fix this by manually selecting the most derived metaclass, and
including it in our temporary metaclass.
Also, `__prepare__` is now …

Fix some issues with six dependency

---

boxsdk/auth/oauth2.py
boxsdk/version.py
test/unit/auth/test_oauth2.py

- Add a TokenResponse object, which is a subclass of BaseAPIJSONObject.
- OAuth2.downscope_token() now returns a TokenResponse object, which
allows users to get other fields of the response, such as
'expires_in'.

Change downscope_token() to return a TokenResponse object

---

boxsdk/object/folder.py
test/unit/object/test_folder.py

Adding ability to set the `can_view_path` body param when constructing
new folder collaborations.
ref: https://developer.box.com/v2.0/reference#add-a-collaboration

Add support for view_path collabs

---

HISTORY.rst
boxsdk/auth/jwt_auth.py
test/unit/auth/test_jwt_auth.py

Fixes #221.
The Box developer console allows a developer to download a
configuration file that specifies how to configure a Box
application.
This commit adds code to parse these config files and apply
the configuration to a JWTAuth instance.

Add methods to configure JWT auth from a config file.

---

requirements-dev.txt
setup.py

The latest version of pytest (3.3.0) dropped support for these
python versions, so we need to install an older version when
we're being run on one of them.

Fix the build for python 2.6 and python 3.3.

---

HISTORY.rst
boxsdk/auth/oauth2.py
boxsdk/client/client.py
boxsdk/object/file.py
boxsdk/object/folder.py
boxsdk/object/group.py
boxsdk/object/item.py
boxsdk/session/box_session.py
boxsdk/version.py
test/unit/conftest.py
test/unit/session/test_box_session.py

Currently, configuration values like user-agent
and API urls are essentially global variables.
This commit adds config to the BoxSession, allowing
each session to override config values.

Add session-specific conf.

---

boxsdk/__init__.py
boxsdk/auth/jwt_auth.py
boxsdk/auth/oauth2.py
boxsdk/exception.py
boxsdk/network/default_network.py
boxsdk/session/box_request.py
boxsdk/session/box_session.py
boxsdk/util/compat.py
boxsdk/util/enum.py
boxsdk/util/json.py
boxsdk/util/log.py
boxsdk/util/lru_cache.py
boxsdk/util/multipart_stream.py
boxsdk/util/ordered_dict.py
docs/source/boxsdk.util.rst
setup.py
test/unit/auth/test_jwt_auth.py
test/unit/object/test_events.py
test/unit/test_exception.py
test/unit/util/test_compat.py
test/unit/util/test_enum.py

Fixes #276
Fixes #270
Fixes #164
Fixes #145
Fixes #117
This commit refactors the Box exception classes to have more useful
string representations.
It also sanitizes sensitive information out of the exceptions and
out of our logging.
Finally, it fixes up some of the documentation for the exception
classes.

Improve exceptions.

---

.travis.yml

In order to make CI run more quickly for PRs, we can skip running tests on push to feature branches (since those will be tested by the PR CI job already).  Pushes on "stable" branches will still be run.

Skip CI on feature branch push

---

boxsdk/util/log.py
test/unit/util/test_log.py

Log sanitization should not attempt to sanitize non-string values,
since they are not guaranteed to be subscriptable.

Add type check in logging sanitizer

---

boxsdk/auth/jwt_auth.py
boxsdk/auth/oauth2.py
boxsdk/client/client.py
boxsdk/client/developer_token_client.py
boxsdk/session/session.py
setup.py
test/functional/conftest.py
test/integration/conftest.py
test/integration/test_retry_and_refresh.py
test/unit/auth/test_jwt_auth.py
test/unit/auth/test_oauth2.py
test/unit/auth/test_redis_managed_oauth2.py
test/unit/conftest.py
test/unit/pagination/test_limit_offset_based_object_collection.py
test/unit/pagination/test_marker_based_object_collection.py
test/unit/pagination/test_page.py
test/unit/session/test_session.py

Previously, auth classes used the network layer directly, while all
other API calls used the session as a network abstraction. This
was not only confusing, but it robbed auth calls of all the session's
features, like automatic retry, user agent, custom headers, etc.
The reason for this was the SDK's architecture. Since the session
handles auth refresh, it needed an auth instance. This commit
refactors the session into unauthorized and authorized parts. Auth
calls now use the unauthorized session, and other API calls use
the authorized session.

Refactor auth to use the session.

---

boxsdk/pagination/limit_offset_based_object_collection.py
test/unit/object/test_group.py
test/unit/pagination/test_limit_offset_based_object_collection.py

Paging APIs return total_count, limit, and offset value. The
V2 API docs talk about how to respect the total_count and
limit fields. But do not state that 'offset' should be interpreted.
So remove the ode that was respecting this value as it can lead
to undefined behavior if it starts to change.
Also add test coverage for existing logic in the paging code.
And fix a broken test in test_group where it was passing params
in the wrong order to Group.get_memberships(). A strange
coincidence that these tests were ever passing???

Stop respecting the 'offset' value in HTTP response.

---

docs/usage/authentication.md

change 
```
service_account = client.user().get()
print('Service Account user ID is {0}'.format(me.id))
```
to 
```
service_account = client.user().get()
print('Service Account user ID is {0}'.format(service_account.id))
```

Correct documentation typo in JWT section

---

setup.py

It looks like in the changelog for request-toolbelt 0.9.1 there was a bug fix for importing pyOpenSSL.
This previously was already broken so it should not affect the SDK.
#408

Upgrading request-toolbelt to accept 0.9.1

---

setup.py

Context:
Tests were failing for all python builds on master because xdist failed to load.
Reason being - from xdist Changelog:
#426: pytest-xdist now uses the new pytest_report_to_serializable and pytest_report_from_serializable hooks from pytest 4.4 (still experimental). This will make report serialization more reliable and extensible.
This also means that pytest-xdist now requires pytest>=4.4.
Python SDK uses pytest version before 4.0.0. Upgrading to 4.4.0 seems to cause some issues and will require refactoring of certain tests.
In the interim looks like locking down xdist to anything prior to 1.28.0 will suffice.

Locking down xdist to any version prior to 1.28.0 because of pytest 4.4.0 dependency

---

docs/search.md
docs/usage/authentication.md
docs/usage/collaboration.md
docs/usage/collaboration_whitelist.md
docs/usage/collections.md
docs/usage/comments.md
docs/usage/device_pin.md
docs/usage/events.md
docs/usage/files.md
docs/usage/folders.md
docs/usage/group.md
docs/usage/legal_hold.md
docs/usage/metadata.md
docs/usage/metadata_cascade_policies.md
docs/usage/retention_policy.md
docs/usage/storage_policy.md
docs/usage/task.md
docs/usage/terms_of_service.md
docs/usage/trash.md
docs/usage/user.md
docs/usage/watermarking.md
docs/usage/web_link.md
docs/usage/webhook.md

I've tagged the majority of code samples to an endpoint for usage in the new developer documentation.

Tag code samples for usage in developer docs

---

docs/usage/folders.md

Reduced the line length for the `get_folders_id` sample in order to make it render nicely on box.dev

Limit line length for get_folders_id

---

docs/usage/folders.md

Update the get_folders_id sample to apply Box' Python code standards.

Update get_folders_id sample to code standards

---

AUTHORS.rst
HISTORY.rst
boxsdk/object/events.py
docs/usage/events.md
test/unit/object/test_events.py

Minor changes to the pr originally submitted by @capk1rk. The fields `created_after` and `created_before` only work with enterprise events. Although if you include these fields with the stream_type set to `ALL` the events that is returned is not indicative of the range set.
We altered the original function to only allow enterprise events by setting the `admin_logs` manually for `stream_type`.
A test was added as well that asserts more importantly(than the response) that the request sent over has the correct query parameters. Readme was also updated for events.

Support for adding enterprise events with date filter.

---

boxsdk/object/folder.py

I'd like to have this document fixed: https://box-python-sdk.readthedocs.io/en/latest/boxsdk.object.html#boxsdk.object.folder.Folder.get_items
Per https://github.com/box/box-python-sdk/issues/366,
> the "limit" actually refers to the limit on items you get back from the API per page. 
This limitation should be reflected to the above doc.
I see that the description of `limit` parameter of other class [Collection](https://box-python-sdk.readthedocs.io/en/latest/boxsdk.object.html#boxsdk.object.collection.Collection.get_items) and [Trash](https://box-python-sdk.readthedocs.io/en/latest/boxsdk.object.html#boxsdk.object.trash.Trash.get_items) have already reflected this point. I hope this will be corrected for "Folder".

Fix on pydoc of get_items of folder.py

---

boxsdk/client/client.py
test/unit/client/test_client.py

Previously, the client.downscope_token() method assumed that an
access token was available, but for JWT auth applications a token
is not generated until the first API call is made; this causes
token exchange to fail.  The downscope method now attempts to
generate an access token if one is not present, before performing
the token exchange.

Ensure that token exchange works before an API call is made

---

AUTHORS.rst
HISTORY.rst
boxsdk/object/events.py

Per #463, I updated the `get_admin_events` function to properly handle the case where the `event_types` optional parameter is omitted.
Fixes #463.

Fixed `get_admin_events` Optional `event_types` Parameter

---

AUTHORS.rst
HISTORY.rst
boxsdk/object/file.py
boxsdk/object/folder.py
test/unit/object/test_file.py
test/unit/object/test_folder.py

Added parameters for all attributes explicitly mentioned in the API reference for uploads*, plus added an `additional_attributes` dict that can be optionally filled with key-value pairs with any other attributes the user wants to modify.
This fixes #472.
*See [here for uploading new files](https://developer.box.com/en/reference/post-files-content/) and [here for uploading new file versions](https://developer.box.com/en/reference/post-files-id-content/).

Support additional file attributes on upload (#472)

---

HISTORY.rst
boxsdk/object/file.py
boxsdk/object/folder.py
boxsdk/object/item.py
test/unit/object/test_file.py
test/unit/object/test_folder.py

When uploading a file, we can combine the preflight check and the request for an accelerator URL into a single OPTIONS request, since both actions target the same endpoint.

Combine preflight and accelerator calls for uploads (#475)

---

boxsdk/object/file.py
boxsdk/object/folder.py
test/unit/object/test_file.py
test/unit/object/test_folder.py

Small iteration on #473; changing file attribute parameters to be the same as those in the API, as there's no good reason to differ from them.

Rename upload method parameters to align with API

---

HISTORY.rst
boxsdk/session/session.py

Release of the Python SDK version 2.7.0 contained new logic in `_get_retry_request_callable` that prevented chunked uploads from working. 
The  new logic in the 2.7.0 release in `_get_retry_request_callable` method was reading the `data` dictionary passed in every request. However, for chunked uploads, `data` is a byte stream and not a dictionary, so the reading of the data fails. The fix in this PR is a simple try block that reads the `data` parameter when it is an object and doesn't when the `data` is a byte stream.

Fix for `_get_retry_request_callable` so chunked uploads continue to work

---

HISTORY.rst
boxsdk/client/client.py
test/unit/client/test_client.py
test/unit/object/test_file.py

- Adds shared_link kwarg to Client.downscope_token. If shared link is sent as an arg in the method call, the downscoped token will be scoped to the resource the shared link references.
- Adds unit test for Client.downscope_token with share_link sent as an arg, and shared_link and item not sent as an arg.

Add support for token exchange using shared links

---

HISTORY.rst
boxsdk/object/file.py
boxsdk/object/folder.py
test/unit/object/conftest.py
test/unit/object/test_file.py
test/unit/object/test_folder.py

Added the ability to pass in a SHA1 value for file uploads. It will sent in the headers to the API with the following key `Content-MD5`.

Add the ability to pass in a SHA1 value for file uploads

---

docs/usage/search.md

search() doesn't take any arguments - need to pass the arguments through a query

Update search.md to correct the metadata example

---

HISTORY.rst
boxsdk/object/base_object.py
boxsdk/object/collaboration.py
test/unit/object/test_collaboration.py

This is to address issue #528. When a collaboration role is updated to an owner, the endpoint returns a 204 with no JSON response instead of the 200 with a JSON response that all other updates return. The SDK was throwing an error when a 204 is returned and this PR addresses the issue.
Wrote an automated test and did manual testing.

Fix bug with updating a collaboration role to owner

---

HISTORY.rst

Some copypasta had them using the ios repo, rather than Python. I was confused for a little bit trying to understand why there was so much C in the python sdk.

Fix HISTORY links to use correct repo

---

boxsdk/object/file.py
test/unit/object/test_file.py

Also update a comment. This can happen if the dimensions aren't found or if the file is very old and the representations have been removed. Fixes issue #596.

Fix bug when thumbnail representations are not found

---

docs/usage/collaboration.md

Adding Group Variant Tag for the dev docs ticket 464

Adding group variant tag for devdocs

---

.travis/install.sh
HISTORY.rst

Fix related to the pyenv change. Described [here](pyenv/pyenv#1906).

Fix PyPy build

---

setup.py

This limit is set, because >=3.5.0 versions require Rust

dependencies: Limiting cryptography library version to <3.5.0

---

README.rst
docs/usage/authentication.md

docs: Document "params" usage for making manual API calls

---

HISTORY.rst

Failing build: https://github.com/box/box-developer-changelog/actions/runs/1554484687

docs: Fix spelling error in changelog

---

boxsdk/object/base_endpoint.py
boxsdk/object/base_item.py
boxsdk/object/base_object.py
boxsdk/object/collaboration.py
boxsdk/object/comment.py
boxsdk/object/events.py
boxsdk/object/file.py
boxsdk/object/folder.py
boxsdk/object/item.py
boxsdk/object/metadata.py
boxsdk/object/metadata_template.py
boxsdk/object/search.py
boxsdk/object/storage_policy.py
boxsdk/object/terms_of_service.py
boxsdk/object/user.py
boxsdk/object/web_link.py
test/functional/test_events.py
test/functional/test_item_info.py
test/unit/object/test_base_item.py
test/unit/object/test_base_object.py
test/unit/object/test_item.py
test/unit/object/test_metadata_template.py
test/unit/object/test_retention_policy.py
test/unit/object/test_storage_policy_assignment.py
test/unit/object/test_task.py
test/unit/object/test_task_assignment.py
test/unit/object/test_terms_of_service.py
test/unit/object/test_user.py
test/unit/object/test_web_link.py
test/unit/object/test_webhook.py

BREAKING CHANGE: Enforcing using keyword only arguments in functions :
- `copy()` in `base_item.py` `file.py`
- `create_shared_link()` in `item.py`, `web_link.py`
- `get_shared_link()` in `item.py`, `web_link.py`
- `remove_shared_link()` in `item.py`
- `get()` in `base_object.py`, `item.py`
- `update_info()` in `base_object.py`, `collaboration.py`, `item.py`, `metadata_template.py`
- `delete()` in `base_object.py`, `folder.py`, `item.py`, `user.py`
Closes: SDK-1904

feat!: Change some methods signatures to accept keyword only arguments

---

README.rst
boxsdk/object/search.py
boxsdk/util/api_call_decorator.py
boxsdk/util/deprecation_decorator.py
docs/usage/search.md
test/unit/object/test_search.py

feat: Deprecate `use_index` param from MDQ of files/folders

---

.github/workflows/build.yml
boxsdk/util/enum.py
tox.ini

Added support for Python 3.8, 3.9, pypy-3.7, pypy-3.8
Closes: SDK-1988

feat: Add support to new python versions

---

setup.py

* Switch the main URL to the GitHub repo. The opensource home page isn't particularly useful - when coming from PyPI, I'm already interested in this specific project.
* Add a changelog link - PyPI will render this in the sidebar with a special link, as at e.g. https://pypi.org/project/django-htmx/ . This helps when upgrading - I normally visit PyPI page and hunt for the changelog link so I can read about changes.

docs: Update URL's in setup.py

---

boxsdk/exception.py
boxsdk/object/__init__.py
boxsdk/util/enum.py
boxsdk/util/log.py
docs/usage/sign_requests.md

fix: Add missing `box_sign` object to `__all__` list

---

boxsdk/object/file.py
boxsdk/util/datetime_formatter.py
docs/source/boxsdk.util.rst
setup.py
test/conftest.py
test/unit/object/test_file.py
test/unit/util/test_datetime_formatter.py

feat: Add setting `disposition_at` field for files under retention

---

boxsdk/object/base_item.py
boxsdk/object/file.py
boxsdk/object/folder.py
boxsdk/object/item.py
test/integration_new/conftest.py
test/integration_new/object/file_itest.py
test/integration_new/object/folder_itest.py
test/unit/object/conftest.py
test/unit/object/test_file.py
test/unit/object/test_folder.py
test/unit/object/test_item.py

feat: Add support for editable shared links for files

---

boxsdk/auth/server_auth.py
test/unit/auth/test_jwt_auth.py

fix: Retry JWT auth when got error: required unique `jti` claim.

---

boxsdk/util/log.py
test/unit/util/test_log.py

feat: Sanitize proxy credentials

---

README.md

According to Change Log documentation, logging_network support was [removed in version 2.0.0](https://github.com/box/box-python-sdk/blob/main/CHANGELOG.md#200). README documentation was never updated to reflect this removal. This PR resolves that discrepancy between docs and changelog.
This PR replaces [PR #783 ](https://github.com/box/box-python-sdk/pull/783)

docs: Remove obsolete `LoggingNetwork` documentation from `README`

---

boxsdk/session/session.py
test/unit/session/test_session.py

fix: Retry `CCG` and `JWT` authentication requests on connection reset error

---

boxsdk/session/session.py
test/unit/session/test_session.py

fix: Retry `Connection broken` and `Connection reset` requests errors

---

README.md

docs: Add section in `README.md` about FIPS

---

boxsdk/util/chunked_uploader.py

fix: `ChunkedUploader` Resume Not Closing `ThreadPoolExecutor` Instances

---

boxsdk/client/client.py
boxsdk/object/sign_template.py
docs/source/boxsdk.object.rst
docs/usage/sign_requests.md
docs/usage/sign_templates.md
test/integration_new/object/sign_template_itest.py
test/unit/client/test_client.py
test/unit/object/conftest.py
test/unit/object/test_sign_templates.py

Tell @PJSimon Dave Rodgers says hi :)

feat: adds get sign template and get sign templates methods on Client

---

.github/workflows/build.yml
.github/workflows/integration-tests.yml
README.md
setup.py
tox.ini

chore: Support Python 3.11

---

setup.py

Fixes https://github.com/box/box-python-sdk/issues/850
Since request 2.30 supports both urllib3 1.26+ and urllib3 2.0+ we decided to remove constraints to urllib<2. (https://github.com/psf/requests/issues/6432)

fix: Remove restriction to version <2 of `urllib3` library

---

boxsdk/auth/oauth2.py

The type annotation for the OAuth access token is incorrect

fix: fix the type annotation for the OAuth access token

---

docs/usage/classifications.md

Because the Classification is using the `metadata_template` object, so only need to remove the example code.

fix: Remove delete classification

---

test/integration_new/object/sign_request_itest.py

Add test for sign request with signer group ID

test: Sign request signer group ID

---

boxsdk/object/file.py
test/unit/object/test_file.py

Closes: SDK-3474
I'm using the `BoxException` not `BoxAPIException` because normally, the `BoxAPIException` will parse from response body but not any custom exception.

fix: Update exception file get download URL

---

boxsdk/object/file.py
boxsdk/object/folder.py
boxsdk/object/upload_session.py
docs/usage/configuration.md
docs/usage/files.md
setup.py
test/integration_new/object/folder_itest.py
test/unit/object/test_file.py
test/unit/object/test_folder.py
test/unit/object/test_upload_session.py

feat: Use upload session `urls` for chunk upload

---

boxsdk/client/client.py
docs/usage/sign_requests.md
test/integration_new/context_managers/box_sign_request.py
test/integration_new/object/sign_request_itest.py
test/unit/client/test_client.py

Some of the params (`parent_folder_id` and `files`)  are no longer required since https://github.com/box/box-openapi/commit/797a90d21024acb03354328cd921c989fac36f4f

feat: add create sign request function with different required parameters

---

docs/usage/folders.md

Replace `client.folders` with `client.folder`
When you run the original sample code, you'll get this error:
```
AttributeError: 'Client' object has no attribute 'folders'. Did you mean: 'folder'?
```

docs: Fix sample code for folder locks endpoint 
