demo/example.py
1) Make the code showing 'groups' functionality more robust. Catch all
403 errors and continue
2) Have the folder listing output the names of the items, not the
objects.
3) A few other minor output formatting things.
=> A few improvements to the demo program.

boxsdk/auth/oauth2.py, test/functional/conftest.py, test/unit/auth/test_oauth2.py
Use ``six.moves.urllib.parse.urlencode()`` to correctly encode the query string parameters that make up the OAuth2 authorize URL.
Previously, the URL was constructed via direct string formatting. This meant that if reserved or non-ASCII characters were present in the data, they would be used unencoded in the URL. This was particularly
problematic with the ``redirect_uri`` query string parameter:
- It is itself a URI and therefore likely to contain reserved characters.
- It is user-supplied and therefore has the possibility of containing non-ASCII unicode characters.
The correct encoding of characters in URLs is specified in various Internet RFCs, which the ``urllib`` package has been designed to match. So using ``urllib`` fixes these problems.
This commit also corrects some related …
=> Use urllib for better OAuth2 URL construction

README.rst
Hope this help others while trying to get folder and file name strings.
=> Add an example for retrieving both a folder and file name.

README.rst
Reverts box/box-python-sdk#12
@djgoku has not signed the CLA. I merged the PR by mistake. I will re-introduce the change when @djgoku sign the CLA.
=> Revert "Add an example for retrieving both a folder and file name."

README.rst
Give an example of how to move a file to a folder.
=> Add example on how to move a file to a folder.

demo/auth.py, demo/example.py
Also support py2.6, py3, and pypy with the demo.
Fixes #7 Fixes #10
=> Improve demo code by making it more robust.

README.rst, boxsdk/object/file.py, boxsdk/object/metadata.py, demo/example.py, docs/source/boxsdk.object.rst, test/unit/object/test_metadata.py
=> Add support for metadata.

HISTORY.rst, setup.py, tox.ini
Add HISTORY file to track changes.
=> Bump version to 1.1.0.

README.rst
Saw this while reading last commits.
=> Fix typo in docs, cosmetic noops

boxsdk/object/base_object.py, boxsdk/object/folder.py, boxsdk/object/group_membership.py, boxsdk/object/search.py, boxsdk/util/translator.py, docs/source/boxsdk.object.rst, docs/source/boxsdk.util.rst, test/unit/conftest.py, test/unit/object/conftest.py, test/unit/object/test_translator.py, test/unit/util/test_translator.py
=> Modify Translator to return BaseObject by default, not None.

boxsdk/client.py, boxsdk/object/search.py, test/unit/object/conftest.py, test/unit/object/test_search.py
Added mdfilters param to search object
=> Add support for searching by metadata value (Fixes #36)

.pylintrc, boxsdk/object/file.py, boxsdk/object/folder.py, boxsdk/object/item.py, demo/example.py, test/unit/object/conftest.py, test/unit/object/test_file.py, test/unit/object/test_folder.py
Supports both new uploads and updating existing files on Box. I also
added a new example in demo/example.py.
=> Add Box Accelerator Support

HISTORY.rst, boxsdk/object/item.py, test/unit/object/test_item.py, tox.ini
=> Support unshared_at for getting shared links

HISTORY.rst, README.rst, boxsdk/__init__.py, boxsdk/auth/jwt_auth.py, boxsdk/auth/oauth2.py, boxsdk/client.py, boxsdk/util/compat.py, docs/source/boxsdk.auth.rst, docs/source/boxsdk.util.rst, requirements.txt, setup.py, test/unit/auth/test_jwt_auth.py, test/unit/auth/test_oauth2.py, test/unit/test_client.py, test/unit/util/test_compat.py
https://developers.box.com/developer-edition/
Adds a new auth class, JWTAuth, to handle the new auth types.
Adds a new client method, `create_user`, to facilitate creating app users.
=> Add support for Box Developer Edition.

.travis.yml
According to http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade, it has tons of benefit.
=> Migrate to run test on travis with container based infra

.travis.yml, .travis/install.sh, .travis/run.sh, HISTORY.rst, README.rst, setup.py
Add support and testing for PyPy 4.0.
=> Add support and testing for PyPy 4.0

HISTORY.rst, boxsdk/client.py, setup.py, test/unit/test_client.py
=> Add limit, offset, and filter_term to client.users()

README.rst
Any and all feedback is welcome!
=> Adding metadata search examples (fixes #104)

AUTHORS.rst, CONTRIBUTING.rst, HISTORY.rst, README.rst, boxsdk/__init__.py, boxsdk/client/__init__.py, boxsdk/client/client.py, boxsdk/client/developer_token_client.py, boxsdk/client/logging_client.py, boxsdk/config.py, boxsdk/session/box_session.py, docs/source/boxsdk.client.rst, docs/source/boxsdk.rst, docs/source/boxsdk.util.rst, setup.py, test/integration/test_as_user.py, test/integration/test_with_shared_link.py, test/unit/client/__init__.py, test/unit/client/test_client.py
* Use custom user agent for requests to Box.
* Add LoggingClient and DevelopmentClient classes.
=> Bump version to 1.5.0.

boxsdk/auth/jwt_auth.py
=> Add kwargs to JWTAuth constructor

README.rst
Fixes #261 , but now in master instead of 1.5
Duplicates #262 , which will be closed since there are merging errors with 1.5
=> updated make_request to include info about passing a body

demo/Shared Link.ipynb
=> Update Shared Link.ipynb

boxsdk/config.py
=> Update authorize URL

HISTORY.rst, boxsdk/object/base_object.py, test/unit/object/test_base_object.py
=> Fix API object equality test

HISTORY.rst, boxsdk/client/client.py, boxsdk/object/folder.py, boxsdk/object/group.py, boxsdk/object/search.py, test/functional/test_delete.py, test/functional/test_file_upload_update_download.py, test/functional/test_item_info.py, test/unit/client/test_client.py, test/unit/object/test_folder.py, test/unit/object/test_group.py, test/unit/object/test_search.py
=> Use paging iterators for all collection-returning methods

docs/usage/authentication.md, docs/usage/webhook.md
Adjusted to access_token based on the response values coming back from the downscope token request.
Example dump of response object:
`{'_response_object': {u'access_token': u'REDACTED',
u'expires_in': 3772,
u'issued_token_type': u'urn:ietf:params:oauth:token-type:access_token',
u'restricted_to': [{u'object': {u'etag': u'0',
u'id': u'REDACTED',
u'name': u'level 1',
u'sequence_id': u'0',
u'type': u'folder'},
u'scope': u'base_preview'},
{u'object': {u'etag': u'0',
u'id': u'43141662407',
u'name': u'level 1',
u'sequence_id': u'0',
u'type': u'folder'},
u'scope': u'item_download'}],
u'token_type': u'bearer'},
u'access_token': u'REDACTED',
u'expires_in': 3772,
u'issued_token_type': u'urn:ietf:params:oauth:token-type:access_token',
u'restricted_to': [{u'object': {u'etag': u'0',
u'id': u'REDACTED', …
=> Change accessToken to access_token in response

docs/usage/files.md
=> Fixed minor typos

boxsdk/client/client.py, setup.py, test/unit/client/test_client.py
- https://jira.inside-box.net/browse/SDK-1215
- Add marker based pagination for listing users
- Added `use_marker` and `marker` parameters to users method in `client.py`
- Return marker paginator if `use_marker` parameter is true
- Added unit test
=> Add marker based pagination for listing users

setup.py
Will create an issue and add explanation once I can get this to pass. :)
=> Pin coverage package to fix backwards-incompatibility

HISTORY.rst, ISSUE_TEMPLATE.md, README.rst, boxsdk/auth/jwt_auth.py, boxsdk/auth/oauth2.py, boxsdk/client/client.py, boxsdk/object/base_object.py, boxsdk/object/events.py, boxsdk/object/item.py, boxsdk/object/metadata.py, boxsdk/pagination/box_object_collection.py, boxsdk/pagination/limit_offset_based_object_collection.py, boxsdk/pagination/marker_based_object_collection.py, docs/usage/authentication.md, docs/usage/events.md, docs/usage/files.md, docs/usage/group.md, docs/usage/metadata.md
Also updated old links to docs.
=> Add additional metadata template samples for dev docs.

.gitignore
Add release script to repo to speed up releases.
=> Add release script

docs/usage/events.md
Add and tag separate samples for enterprise events and filtered enterprise events
=> Add and tag separate samples for enterprise events and filtered enterprise events

boxsdk/object/api_json_object.py, boxsdk/pagination/box_object_collection.py, boxsdk/pagination/page.py, boxsdk/util/log.py
=> Fix deprecation warnings for collections.abc imports

HISTORY.rst, boxsdk/object/item.py
=> Allow ints to be passed in as item IDs

docs/usage/user.md
We changed the ID of this endpoint in the dev docs and therefore the samples need new IDs as well.
=>  Update sample tag for transfer folder

HISTORY.rst, boxsdk/object/search.py, boxsdk/pagination/box_object_collection.py, boxsdk/pagination/marker_based_object_collection.py, docs/usage/search.md, test/unit/object/test_search.py
Did manual testing in addition to unit tests.
=> Add metadata query functionality

.github/ISSUE_TEMPLATE/config.yml, .travis.yml, CONTRIBUTING.rst
To update your existing local environment, run these commands:
```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```
=> Update default branch from `master` to `main`

.travis/install.sh, boxsdk/object/file.py, test/unit/object/test_file.py, test/unit/object/test_search.py
Fix unit test for python<3.6
Fix code according to Pylint
=> Fix Travis CI for Python 2 and Pylint

HISTORY.rst, boxsdk/client/client.py, boxsdk/object/retention_policy_assignment.py, docs/usage/retention_policy.md, test/unit/object/conftest.py, test/unit/object/test_file.py, test/unit/object/test_retention_policy_assignment.py
=> Story: New API for get files and file versions under retention

boxsdk/object/events.py, test/unit/object/test_events.py
Fix for https://github.com/box/box-python-sdk/issues/647
=> fix(Events)!: Add missing parameter `stream_position` to get_admin_events method

setup.py
=> fix: Added `py.typed` file for `mypy` to recognise type hints

docs/usage/files.md, docs/usage/folders.md, docs/usage/web_link.md
=> docs: Fix examples of moving and copying items

boxsdk/object/file.py, boxsdk/object/folder.py, boxsdk/object/upload_session.py
=> fix: Fix chunked upload

boxsdk/auth/ccg_auth.py, boxsdk/auth/jwt_auth.py, boxsdk/auth/redis_managed_jwt_auth.py, boxsdk/auth/server_auth.py, docs/source/boxsdk.auth.rst, setup.py, test/conftest.py, test/unit/auth/test_ccg_auth.py, test/unit/auth/test_jwt_auth.py, test/unit/client/test_client.py
=> feat: Add support for Client Credentials Grant authentication method

README.md, VERSIONS.md
Added details about version support policy.
=> docs: Information about supported versions

boxsdk/object/metadata_template.py, test/integration_new/object/metadata_template_itest.py, test/unit/object/test_metadata_template.py
=> fix: Add missing fields to metadata template field

boxsdk/object/upload_session.py, test/unit/object/test_upload_session.py
=> fix: Upload session commit return None on 202

boxsdk/client/client.py, boxsdk/object/base_item.py, boxsdk/object/events.py, boxsdk/object/file.py, boxsdk/object/folder.py, boxsdk/object/item.py, boxsdk/object/web_link.py, boxsdk/util/datetime_formatter.py, test/integration_new/object/file_itest.py, test/unit/client/test_client.py, test/unit/object/conftest.py, test/unit/object/test_chunked_upload.py, test/unit/object/test_events.py, test/unit/object/test_file.py, test/unit/object/test_folder.py, test/unit/object/test_item.py, test/unit/object/test_web_link.py, test/unit/util/test_datetime_formatter.py
=> feat: Add support for multiple date time formats

boxsdk/config.py, docs/usage/configuration.md
=> docs: Document changing default configuration settings

docs/usage/README.md
=> docs: Document how to get raw json response

README.md, boxsdk/auth/jwt_auth.py, boxsdk/auth/oauth2.py
=> docs: Improve authentication documentation

boxsdk/client/client.py, docs/usage/sign_requests.md, test/unit/client/test_client.py, test/unit/object/test_sign_request.py
=> feat: Add `redirect_url` and `declined_redirect_url` fields to Sign Request

boxsdk/client/client.py, test/integration_new/context_managers/box_retention_policy.py, test/integration_new/context_managers/box_retention_policy_assigment.py, test/integration_new/object/file_itest.py, test/integration_new/object/retention_policy_assignement_itest.py, test/integration_new/object/user_itest.py, test/unit/client/test_client.py, test/unit/object/test_retention_policy.py, test/unit/object/test_retention_policy_assignment.py
=> feat: Add support for modifiable retention policies & enable deleting retention policy assignment

boxsdk/network/default_network.py, boxsdk/session/session.py, test/functional/test_file_upload_update_download.py, test/integration/test_as_user.py, test/integration/test_retry_and_refresh.py, test/integration/test_with_shared_link.py, test/integration_new/object/user_itest.py, test/unit/network/test_network.py, test/unit/session/test_session.py
=> fix: Do not log the content of downloaded file

boxsdk/object/folder.py, boxsdk/util/chunked_uploader.py, docs/usage/files.md
=> feat: Fix closing file after chunked upload

boxsdk/session/box_request.py, boxsdk/session/session.py, test/unit/session/test_session.py
Closes: SDK-2732
Fixes: #770, #765, #766
=> fix: Renew connection when Connection reset error occurs

setup.py, test/integration_new/object/user_itest.py
=> fix: Update `pyjtw` dependency to work with Python 3.10

boxsdk/object/terms_of_service.py, test/unit/object/test_terms_of_service.py
=> fix: Fix index error when getting an empty list of user term of service statuses

boxsdk/session/session.py, test/unit/session/test_session.py
=> fix: Specify which exceptions should be retried

docs/usage/files.md
Small change to automatically close the downloaded file. 
Fixes [DDOC-754](https://jira.inside-box.net/browse/DDOC-754)
=> docs: Improve file download example to close file after download is complete

boxsdk/object/events.py, docs/usage/events.md
=> docs: Document default value of limit parameter in events

boxsdk/client/client.py, boxsdk/object/retention_policy.py, test/integration_new/object/retention_policy_assignement_itest.py, test/integration_new/object/retention_policy_itest.py, test/unit/client/test_client.py, test/unit/object/test_retention_policy.py
=> feat: Update `retention_policies` and `retention_policy_assignments`

boxsdk/network/default_network.py
=> fix: Stop processing data for logging when logging is disabled and cache response `json`

boxsdk/client/client.py, test/unit/client/test_client.py
=> fix: do not retry creating a ZIP when response code is 202

docs/usage/authentication.md
=> docs: Update authentication.md

.github/workflows/build-and-test-daily.yml
=> chore: fix cron job notification
